[aliases]
test=pytest

[metadata]
description-file = README.md

[tool:pytest]
testpaths = sp_validation
addopts =
  --verbose
  --pycodestyle
  --pydocstyle
  --cov=sp_validation
  --cov-report=term
  --cov-report=xml
  --junitxml=pytest.xml

[pycodestyle]
# E712 ignore to be revised, not currently compatible with np.where statements
ignore = W503,E712

[pydocstyle]
convention = numpy
add-ignore = D105,D107
