# Config file for masking and calibration.
# Standard cuts without coverage mask, type v1.X.4.

# General parameters (can also given on command line)
params:
  input_path: shape_catalog_comprehensive_ngmix.hdf5
  cmatrices: False
  sky_regions: False
  verbose: True

# Masks
## Using columns in 'dat' group (ShapePipe flags)
dat:
  # SExtractor flags
  - col_name: FLAGS
    label: SE FLAGS
    kind: equal
    value: 0

  # Number of epochs
  - col_name: N_EPOCH
    label: r"$n_{\rm epoch}$"
    kind: greater_equal
    value: 2

  # Magnitude range
  - col_name: mag
    label: mag range
    kind: range
    value: [15, 30]

  # ngmix flags
  - col_name: NGMIX_MOM_FAIL
    label: "ngmix moments failure"
    kind: equal
    value: 0

  # invalid PSF ellipticities
  - col_name: NGMIX_ELL_PSFo_NOSHEAR_0
    label: "bad PSF ellipticity comp 1"
    kind: not_equal
    value: -10
  - col_name: NGMIX_ELL_PSFo_NOSHEAR_1
    label: "bad PSF ellipticity comp 2"
    kind: not_equal
    value: -10

# Metacal parameters
metacal:
  # Ellipticity dispersion
  sigma_eps_prior: 0.34

  # Signal-to-noise range
  gal_snr_min: 10
  gal_snr_max: 500

  # Relative-size (hlr / hlr_psf) range
  gal_rel_size_min: 0.5
  gal_rel_size_max: 3

  # Correct relative size for ellipticity?
  gal_size_corr_ell: False

  # Weight for global response matrix, None for unweighted mean.
  # Unweighted for image sims: no weights anywhere in sim m-bias (#227).
  global_R_weight: null

  # Subtract additive bias (mean shear)? Use False for constant-shear
  # image sims
  additive_correction: False
