configfile: "config/config.yaml"


def find_cosmosis_inputs():
    chain = config["chain"]
    print("hi")
    for ini_dir in config["ini_dirs"]:
        ini_file = Path(ini_dir) / f"cosmosis_pipeline_{chain}.ini"
        if os.path.exists(ini_file):
            return ini_file
    raise FileNotFoundError(
        f"Cosmosis input file not found for chain {chain} in specified directories."
    )


rule get_bestfit_theory:
    input:
        inference_ini=find_cosmosis_inputs(),
    output:
        bestfit_values_ini=f"results/{config['chain']}/bestfit_values.ini",
        cosmosis_ini=f"results/{config['chain']}/cosmosis.ini",
        data_vector=f"results/{config['chain']}/bestfit_theory.txt",
    params:
        bestfit_dir=f"results/{config['chain']}",
    script:
        "scripts/get_bestfit_theory.py"


rule paper_plots:
    input:
        theory_data_vector=f"/n17data/cdaley/unions/sp_validation/cosmo_inference/notebooks/2D_cosmic_shear_paper_plots/results/{config['chain']}/bestfit_theory.txt",
        xi_reporting="/n17data/cdaley/unions/sp_validation/notebooks/cosmo_val/output/{version}_xi_minsep={min_sep}_maxsep={max_sep}_nbins={nbins}_npatch={npatch}.txt".format(
            **config
        ),
        xi_integration="/n17data/cdaley/unions/sp_validation/notebooks/cosmo_val/output/{version}_xi_minsep={min_sep_int}_maxsep={max_sep_int}_nbins={nbins_int}_npatch={npatch}.txt".format(
            **config
        ),
    output:
        int_vs_rep="/n17data/cdaley/unions/pure_eb/results/paper_plots/{version}_eb_minsep={min_sep}_maxsep={max_sep}_nbins={nbins}_minsepint={min_sep_int}_maxsepint={max_sep_int}_nbinsint={nbins_int}_npatch={npatch}_integration_vs_reporting.png".format(
            **config
        ),
        xis="/n17data/cdaley/unions/pure_eb/results/paper_plots/{version}_eb_minsep={min_sep}_maxsep={max_sep}_nbins={nbins}_minsepint={min_sep_int}_maxsepint={max_sep_int}_nbinsint={nbins_int}_npatch={npatch}_xis.png".format(
            **config
        ),
        ptes="/n17data/cdaley/unions/pure_eb/results/paper_plots/{version}_eb_minsep={min_sep}_maxsep={max_sep}_nbins={nbins}_minsepint={min_sep_int}_maxsepint={max_sep_int}_nbinsint={nbins_int}_npatch={npatch}_ptes.png".format(
            **config
        ),
        cov="/n17data/cdaley/unions/pure_eb/results/paper_plots/{version}_eb_minsep={min_sep}_maxsep={max_sep}_nbins={nbins}_minsepint={min_sep_int}_maxsepint={max_sep_int}_nbinsint={nbins_int}_npatch={npatch}_cov.png".format(
            **config
        ),
    params:
        version=config["version"],
        min_sep=lambda params: float(config["min_sep"]),
        max_sep=lambda params: int(config["max_sep"]),
        nbins=lambda params: int(config["nbins"]),
        min_sep_int=lambda params: float(config["min_sep_int"]),
        max_sep_int=lambda params: int(config["max_sep_int"]),
        nbins_int=lambda params: int(config["nbins_int"]),
        npatch=lambda params: int(config["npatch"]),
    threads: 1
    script:
        "paper_plots.py"
