#parameters used elsewhere in this file
[DEFAULT]
SAMPLES_FILE = /home/guerrini/sp_validation/notebooks/cosmo_val/output/rho_tau_stats//samples_SP_v1.4-P1+3.npy
FITS_FILE = data/SP_v1.4-P1+3/cosmosis_SP_v1.4-P1+3.fits
# Specify the directory of your cosmological CosmoSIS library
COSMOSIS_DIR = /home/guerrini/cosmosis-standard-library


[pipeline]
priors = cosmosis_config/priors_SP_v1.4-P1+3.ini
values = cosmosis_config/values_SP_v1.4-P1+3.ini
modules = consistency camb load_nz_fits linear_alignment projection 2pt_shear add_xi_sys 2pt_like 
likelihoods = 2pt_like 
extra_output = cosmological_parameters/omega_lambda cosmological_parameters/S_8
quiet = F
timing = T
debug = T

[runtime]
sampler = metropolis

[output]
filename = /n17data/sguerrini/mcmc_xi_sys/SP_v1.4-P1+3/w_xi_sys/cut_80/samples_SP_v1.4-P1+3.txt
format = text
lock = F

[metropolis]
samples = 10000000 

[consistency]
file = %(COSMOSIS_DIR)s/utility/consistency/consistency_interface.py
verbose = F

[camb]
file = %(COSMOSIS_DIR)s/boltzmann/camb/camb_interface.py
mode=all
lmax=2508
feedback=0
do_reionization=F
kmin=1e-5
kmax=20.0
nk=200
zmax=5.0
zmax_background=5.0
nz_background=500
halofit_version=takahashi
nonlinear=pk
neutrino_hierarchy=normal
kmax_extrapolate = 500.0

[load_nz_fits]
file = %(COSMOSIS_DIR)s/number_density/load_nz_fits/load_nz_fits.py
nz_file =%(FITS_FILE)s
data_sets = SOURCE

[linear_alignment]
file = %(COSMOSIS_DIR)s/intrinsic_alignments/la_model/linear_alignments_interface.py
method = bk_corrected

[projection]
file = %(COSMOSIS_DIR)s/structure/projection/project_2d.py
ell_min_logspaced = 1.0
ell_max_logspaced = 25000.0
n_ell_logspaced = 400
shear-shear = source-source
get_kernel_peaks = F
verbose = F

[2pt_shear]
file = %(COSMOSIS_DIR)s/shear/cl_to_xi_nicaea/nicaea_interface.so
corr_type = 0  ; shear_cl -> shear_xi

[add_xi_sys]
file = %(COSMOSIS_DIR)s/shear/xi_sys/xi_sys_psf.py
data_file=%(FITS_FILE)s
rho_stats_name=RHO_STATS
xi_plus_name=XI_PLUS
xi_minus_name=XI_MINUS
samples=%(SAMPLES_FILE)s
angle_range_XI_PLUS_1_1=1.0 80.0
angle_range_XI_MINUS_1_1=1.0 80.0


[2pt_like]
file = %(COSMOSIS_DIR)s/likelihood/2pt/2pt_like_xi_sys.py
data_file=%(FITS_FILE)s
gaussian_covariance=F
covmat_name=COVMAT
cut_zeros=F
data_sets=XI_PLUS XI_MINUS
like_name=2pt_like

angle_range_XI_PLUS_1_1= 1.0 80.0
angle_range_XI_MINUS_1_1= 1.0 80.0