; @sc [decision:inference.psf_leakage_model]
[psf_leakage_parameters]
alpha = gaussian 0.0051 0.022
beta = gaussian 0.8098 0.1148

; @sc [decision:inference.intrinsic_alignment_model]
[intrinsic_alignment_parameters]
A = gaussian 0.83 0.7

; @sc [decision:inference.cosmological_parameter_space]
[cosmological_parameters]
ombh2 = gaussian 0.0244 0.00038

; @sc [decision:inference.shear_calibration_prior]
[shear_calibration_parameters]
m1 = gaussian -0.0057 0.014

; @sc [decision:inference.photoz_shift]
[nofz_shifts]
bias_1 = gaussian -0.030 0.018
