# Cosmological parameters
#
Omega_m : 0.25
Omega_v : 0.75
sigma_8 : 0.8
n_spec : 0.95
w0 : -1
wa : 0
omb : 0.044
h0 : 0.7


# Survey and galaxy parameters

# area in degrees
# n_gal,lens_n_gal in gals/arcmin^2

; FOR SHAPEPIPE 3500
area : 2138
sourcephotoz : multihisto
lensphotoz : multihisto
source_tomobins : 1
lens_tomobins : 1
sigma_e : 0.4384
source_n_gal : 7.6

; FOR SHAPEPIPE 1500
; area : 1453
; sourcephotoz : multihisto
; lensphotoz : multihisto
; source_tomobins : 1
; lens_tomobins : 1
; sigma_e : 0.4808326112068524
; source_n_gal : 7.92

# IA parameters
IA : 1
A_ia : 0.0
eta_ia : 0.0
oneplusz0_ia: 0.6

# Covariance paramters
#
# tmin,tmax in arcminutes
tmin : 0.1
tmax : 250
ntheta : 20

# whether to calculate the non-Gaussian part as well
ng : 1
cng : 1

# covariances for shear-shear, shear-pos or pos-pos
ss : true
ls : false
ll : false
filename : out_cov
shear_REDSHIFT_FILE : ./cosmocov_config/dndz_test.txt
clustering_REDSHIFT_FILE : ./cosmocov_config/dndz_test.txt
outdir : data/SP_v1.3_LFmask_8k/covs/
