#!/usr/bin/env python3
"""Calculate angular power spectrum for a single HEALPix mask.

Loads downgraded mask, computes C_ell using healpy.anafast, exports for CosmoCov.
"""

from datetime import datetime
import os

import numpy as np
import healpy as hp


def load_healpix_mask(mask_path: str, verbose: bool = True) -> np.ndarray:
    """Load HEALPix mask from FITS file."""
    if verbose:
        print(f"Loading HEALPix mask: {mask_path}")

    if not os.path.exists(mask_path):
        raise FileNotFoundError(f"Mask file not found: {mask_path}")

    mask = hp.read_map(mask_path, verbose=False)
    nside = hp.npix2nside(len(mask))

    if verbose:
        n_valid = np.sum(mask > 0)
        coverage = n_valid / len(mask)
        print(f"  nside={nside}, valid_pixels={n_valid}, coverage={coverage:.1%}")

    return mask


def calculate_power_spectrum(
    mask: np.ndarray, lmax: int | None = None, verbose: bool = True
) -> tuple[np.ndarray, np.ndarray]:
    """Calculate angular power spectrum of mask using healpy.anafast."""
    nside = hp.npix2nside(len(mask))

    if lmax is None:
        lmax = 3 * nside - 1  # Natural maximum for HEALPix

    if verbose:
        print(f"  Calculating power spectrum up to lmax={lmax}")

    cl = hp.anafast(mask, lmax=lmax)
    ell = np.arange(len(cl))

    if verbose:
        print(f"  Power spectrum calculated: {len(cl)} multipoles")

    return ell, cl


def export_power_spectrum(
    ell: np.ndarray, cl: np.ndarray, nside: int, output_path: str, verbose: bool = True
) -> None:
    """Export power spectrum in CosmoCov format."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    header = (
        f"# UNIONS mask power spectrum for nside={nside}\n"
        f"# Generated by analyze_mask_power_spectrum.py on {datetime.now().strftime('%Y-%m-%d')}\n"
        f"# Format: ell C_ell\n"
        f"# lmax = {len(cl)-1}"
    )

    np.savetxt(output_path, np.column_stack([ell, cl]), fmt="%d %.12e", header=header)

    if verbose:
        print(f"  Exported power spectrum: {output_path}")


def main():
    """Process single mask power spectrum (Snakemake script entry point)."""
    from snakemake.script import snakemake

    mask_path = snakemake.input.mask
    output_path = str(snakemake.output.power_spectrum)

    print("=== Mask Power Spectrum Calculation ===")
    print(f"Input: {mask_path}")
    print(f"Output: {output_path}")

    mask = load_healpix_mask(mask_path)
    nside = hp.npix2nside(len(mask))
    ell, cl = calculate_power_spectrum(mask)
    export_power_spectrum(ell, cl, nside, output_path)

    print("Power spectrum calculation completed.")


if __name__ == "__main__":
    main()
