paths:
   output: ./output

nz:
   subdir: v1.0/nz
   dndz:
      path: dndz
      blind: A

SP_v1.0:
   shape: ngmix
   pipeline: SP
   subdir: v1.0/ShapePipe
   ls: solid
   colour: b
   getdist_colour: (0.0, 0.5, 1.0)
   shear:
      #path: unions_shapepipe_extended_2022_v1.0.fits
      path: unions_shapepipe_2022_v1.0.fits
      label: SP
      e1_bias: 0
      e2_bias: 0
      covmat_file: ./covs/shapepipe_A/cov_shapepipe_A.txt
   psf:
      path: unions_shapepipe_psf_2022_v1.0.2.fits
      label: SP_psf
   star:
      path: unions_shapepipe_star_2022_v1.0.3.fits
      label: SP_star
      e1_col: e1
      e2_col: e2

LF_v1.0:
   shape: lensfit
   pipeline: LF
   subdir: v1.0/Lensfit
   ls: solid
   colour: g
   getdist_colour: (1.0, 0.5, 0.0)
   shear:
      path: lensfit_goldshape_2022v1.fits
      label: LF_Full
      e1_bias: 0
      e2_bias: 0
      covmat_file: ./covs/lensfit_A/cov_lensfit_A.txt
   star:
      path: full_starcat_tmp_1_10_seed_1234.fits
      label: LF_star
      e1_col: e1
      e2_col: e2

LF_v2.0:
   shape: lensfit
   pipeline: LF
   subdir: v2.0/Lensfit
   ls: dashed
   colour: g
   shear:
      path: lensfit_goldshape_2022v2_psf1.fits
      label: LF_Full
      e1_bias: 0
      e2_bias: 0
   star:
      path: Pall_hdu1_THELI_psfs1_mosaic.fits
      e1_col: e1_psf
      e2_col: e2_psf

SP_matched_LF_v1.0:
   shape: ngmix
   pipeline: SP
   subdir: v1.0/matched_LF_SP
   ls: dotted
   colour: b
   getdist_colour: (0.90340530805574, 0.06198853997875753, 0.6527408678603205)
   shear:
      path: masked_matched_unions_shapepipe_extended_2022_v1.0.fits
      label: SP_Match_LF
      e1_bias: -5.6726e-5
      e2_bias: 8.218e-4
      covmat_file: ./covs/shapepipe_matched/cov_shapepipe_matched.txt
   star:
      path: unions_shapepipe_star_2022_v1.0.3.fits
      label: SP_star
      e1_col: e1
      e2_col: e2

LF_matched_SP_v1.0:
   shape: lensfit
   pipeline: LF
   subdir: v1.0/matched_LF_SP
   ls: dashdot
   colour: g
   getdist_colour: (0.0, 0.5, 0.0)
   shear:
      path: masked_lensfit_goldshape_2022v1.fits
      label: LF_Match_SP
      e1_bias: 3.939e-4
      e2_bias: 6.482e-5
      covmat_file: ./covs/shapepipe_matched/cov_shapepipe_matched.txt
   star:
      path: full_starcat_tmp_1_10_seed_1234.fits
      label: LF_star
      e1_col: e1
      e2_col: e2

SP_matched_MP_v1.0:
   pipeline: SP
   ls: dashdot
   colour: b
   getdist_colour: (0.04606552309790213, 0.9780505945532256, 0.37684692395248665)
   shear:
      path: cfis-shapepipe.parquet
      label: SP_Match_MegaPipe
      e1_bias: 0
      e2_bias: 0

SP_matched_LF_fp_v1.0:
   pipeline: SP
   ls: dashed
   colour: b
   getdist_colour: (0.08130806428547999, 0.1463709449188496, 0.674947827197815)
   shear:
      path: matched_footprint_shapepipe.fits
      label: SP_Match LF_Footprint
      e1_bias: 0
      e2_bias: 0
      covmat_file: ./covs/lensfit_matched/cov_lensfit_matched.txt
      
